### ISSUE TITLE
ZClassic Electrum Wallet Sweep Not Working

### ISSUE THREAD

**Issue by Achieveaholics** [BTCP-community/electrum-zcl#198]

**Comment by mexican1973** [comment]
Hi
Normally with your ledger device you dont need a private key because the ledger holds it for you.
This means you can use electrum with your ledger without a private key.
Connect your ledger to the PC via USB
you have to unlock your ledger and then into the Zclassic app.
when you are insideopen electrum software on your pc. 
Then you will see that you connect fine.
Check this medium article also the trouble shooting part:.

https://medium.com/@applicationist/zclassic-ledger-nano-s-guide-554c67033dae

Hope I could help you.
